name: Deploy app

on:
  push:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check app ID
        run: echo ${{ env.APP_ID }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: app_48fb697a-091d-417e-a39e-ee1042c1db8b
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
