name: Deploy app

on:
  push:
    branches: [ "master" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  deployment:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - name: Check app ID
        run: echo ${{ vars.APP_ID }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: ${{ vars.APP_ID }}
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
